databases:
  - name: sigalix
    databaseName: sigalix
    user: sunyin

 services:
 - type: pserv
   name: pgbouncer
   runtime: docker
   plan: standard
   repo: https://github.com/render-oss/docker-pgbouncer
   envVars:
   - key: postgres://sunyin:ZNhJ9ncei7xC0TpofN8vHETDVa3NJZjL@dpg-cn7qcc6v3ddc73co9fkg-a.oregon-postgres.render.com/sigalix
     fromDatabase:
       name: sigalic
       property: connectionString
   - key: POOL_MODE
     value: transaction
   - key: SERVER_RESET_QUERY
     value: DISCARD ALL
   - key: MAX_CLIENT_CONN
     value: 500
   - key: DEFAULT_POOL_SIZE
     value: 50
